fcrepo4-exts/fcrepo-webapp-plus

pom.xml, src/rbacl/webapp/WEB-INF/classes/config/repository.json, src/rbacl/webapp/WEB-INF/classes/spring/auth-master.xml, src/test/java/org/fcrepo/integration/SanityIT.java, src/xacml/webapp/WEB-INF/classes/config/repository.json
See https://jira.duraspace.org/browse/FCREPO-1288
This normalizes the configuration values, bringing this project in line with fcrepo4.
=> normalized configuration values

src/test/java/org/fcrepo/integration/SanityIT.java, src/test/java/org/fcrepo/integration/package-info.java
See: https://jira.duraspace.org/browse/FCREPO-1297
changed license year to 2015
=> updated license header with correct year

pom.xml
=> Update dependencies versions

pom.xml
Partial resolution of: https://jira.duraspace.org/browse/FCREPO-1580
=> Use ${project.version} instead of hardcoded dep versions

src/audit/resources/spring/master.xml
See: https://jira.duraspace.org/browse/FCREPO-1621
=> fix spring config for audit feature

src/rbacl/webapp/WEB-INF/classes/spring/auth-repo.xml, src/xacml/webapp/WEB-INF/classes/spring/repo.xml, src/xacml/webapp/WEB-INF/classes/spring/rest.xml
See: https://jira.duraspace.org/browse/FCREPO-1641
Note: the travis build will fail until fcrepo4/fcrepo4#846 is merged
=> update kernel package names based on proposed upstream changes

pom.xml, src/test/resources/jetty-test.xml
Related to: https://jira.duraspace.org/browse/FCREPO-1643
=> Upgrade jetty-maven-plugin

README.md, pom.xml
https://jira.duraspace.org/browse/FCREPO-1683
=> update scm location

README.md
See: https://jira.duraspace.org/browse/FCREPO-1745
We still need one more maintainer for this. Once we have it, I can add it and rebase.
=> Add maintainer section. Address FCREPO-1745.

README.md
Part of https://jira.duraspace.org/browse/FCREPO-1239
=> Link to Quick Start with WebAC guide on the wiki.

pom.xml
See: https://jira.duraspace.org/browse/FCREPO-1769
=> decouple project.version from fcrepo.version

src/audit/auth-resources/spring/auth-master.xml
- Fixed the line importing the audit config file
Resolves: https://jira.duraspace.org/browse/FCREPO-1855
=> Fixed incorrect class path

src/test/java/org/fcrepo/integration/SanityIT.java, src/test/java/org/fcrepo/integration/package-info.java
Resolves: https://jira.duraspace.org/browse/FCREPO-1583
=> Reformat license headers

pom.xml
Resolves: https://jira.duraspace.org/browse/FCREPO-1838
=> Allow enabling of internal audit with jetty:run

pom.xml
Partial resolution of: https://jira.duraspace.org/browse/FCREPO-1883
=> Remove unnecessary properties from pom.xml

.gitignore, LICENSE, NOTICE, src/test/java/org/fcrepo/integration/SanityIT.java, src/test/java/org/fcrepo/integration/package-info.java
Related to: https://jira.duraspace.org/browse/FCREPO-2066
=> Update source headers to not require annual update

src/rbacl/webapp/WEB-INF/classes/spring/auth-repo.xml, src/xacml/webapp/WEB-INF/classes/spring/auth-repo.xml
Related to: https://jira.duraspace.org/browse/FCREPO-1853
=> Remove auto-registration of the AccessRolesResources component.

src/rbacl/webapp/WEB-INF/web.xml, src/webac/webapp/WEB-INF/web.xml, src/xacml/webapp/WEB-INF/web.xml
Resolves: https://jira.duraspace.org/browse/FCREPO-2083
=> Add servlet filter for handling ETags for static resources

src/webac/webapp/WEB-INF/classes/spring/auth-repo.xml
Resolves: https://jira.duraspace.org/browse/FCREPO-2078
=> Update webac repo.xml configuration to add delegatedPrincipalProvider

pom.xml
Addresses: https://jira.duraspace.org/browse/FCREPO-2091
=> Increment version number to 4.7.0-SNAPSHOT for next development cycle

pom.xml
Resolves: https://jira.duraspace.org/browse/FCREPO-2102
=> Properly configure activemq directory

pom.xml
Follow-on to: https://jira.duraspace.org/browse/FCREPO-1994
=> Change configuration to support mode5

src/audit/resources/logback.xml
Related to: https://jira.duraspace.org/browse/FCREPO-2109
=> Enable inheritance of logging levels

README.md, pom.xml, src/audit/resources/logback.xml
Merge of fix from master to RC branch: https://jira.duraspace.org/browse/FCREPO-2371
=> remove profile for fcrepo-connector-file, which is unmaintained

pom.xml
Addresses https://jira.duraspace.org/browse/FCREPO-2384
Adds apple trees as a dependency.
=> FCREPO-2384

pom.xml
* First pass at adding apple trees
Resolves: https://jira.duraspace.org/browse/FCREPO-2384
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *
**JIRA Ticket**: (link)
* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
A brief description of what the intended result of the PR will be and/or what problem it solves.
A in-depth description of the changes made by this PR. Technical details and possible side effects.
Example:
* Changes x feature to such that y
* Added x
* Removed y
A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as …
=> Add apple-trees

pom.xml
Finalize 4.7.5 release by merging 4.7.5-maintenance into 4.7-maintenance
=> Finalize 4.7.5 release by merging 4.7.5-maintenance into 4.7-maintenance
